tensorlayer/tensorlayer

tensorlayer/layers.py

batch norm add beta gamma initializer

batch norm add beta gamma initializer

---

tensorlayer/files.py

The run() and eval() will run the whole graph from scratch, so combining ops to an array and executing together will result in significant speed-up.

Update files.py, speed up model saving and restoring process.

---

tensorlayer/layers.py

fixes #53
Added a function in layers.py that returns a tf.constant_initalizer that can be passed to DeConv2DLayer as W_int for initalizing the DeConv2DLayer to correspond to channelwise bilinear upsampling. This is used in a number of semantic segmentation approaches such as FCN.

Added deconv2d_bilinear_upsampling_initializer() to layer.py

---

tensorlayer/nlp.py

fix bug of read_words when using python3.5

---

docs/user/tutorial.rst

BasicLSTMCell  should be tf.contrib.rnn.BasicLSTMCell in TF1.0

fix  BasicLSTMCell  for TF1.0

---

.gitignore

ignore `build/` after `python setup.py install`

ignore build/

---

tensorlayer/layers.py

Replace name_reuse with set_keep['name_reuse'] in line 265 of layers.py because name_reuse is undefined in the file.

name_reuse undefined

---

tensorlayer/files.py

Check model file exists before load the params. Matching params in saved model with all GLOBAL_VARIABLES in the graph instead of only check TRAINABLE_VARIABLES.

Minor Changes in load_and_assign_npz_dict

---

tensorlayer/layers.py

Use the tensorflow internal op to replace the operation(may have some help to speed up it), also simplify the old one(same effect but faster to compile)

Update SubPixelConv2d using tf.depth_to_sapce

---

tensorlayer/layers.py

fix bug in deformable CNN

---

tensorlayer/layers.py

add the feed_dict argument for initialize_rnn_state

---

README.md

[preview](https://github.com/lgarithm/tensorlayer/tree/docker)

add docker pull badge

---

docs/modules/db.rst
docs/modules/distributed.rst
tensorlayer/db.py
tensorlayer/distributed.py
tensorlayer/files.py
tensorlayer/iterate.py
tensorlayer/layers.py
tensorlayer/nlp.py

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

fix some doc warnings

---

tensorlayer/layers.py

Remove some useless code mentioned in this [issue](https://github.com/tensorlayer/tensorlayer/issues/301)

remove useless Dropoutwrapper in dynamic rnn

---

example/data/__init__.py
example/tutorial_atari_pong.py
example/tutorial_bipedalwalker_a3c_continuous_action.py
example/tutorial_cartpole_ac.py
example/tutorial_cifar10.py
example/tutorial_cifar10_tfrecord.py
example/tutorial_frozenlake_dqn.py
example/tutorial_frozenlake_q_table.py
example/tutorial_generate_text.py
example/tutorial_image_preprocess.py
example/tutorial_imagenet_inceptionV3_distributed.py
example/tutorial_imdb_fasttext.py
example/tutorial_inceptionV3_tfslim.py
example/tutorial_keras.py
example/tutorial_matrix.py
example/tutorial_mlp_dropout1.py
example/tutorial_mlp_dropout2.py
example/tutorial_mnist.py
example/tutorial_mnist_distributed.py
example/tutorial_mnist_float16.py
example/tutorial_mnist_simple.py
example/tutorial_ptb_lstm.py
example/tutorial_ptb_lstm_state_is_tuple.py
example/tutorial_tfrecord.py
example/tutorial_tfrecord2.py
example/tutorial_tfrecord3.py
example/tutorial_vgg16.py
example/tutorial_vgg19.py
example/tutorial_word2vec_basic.py
tests/testing.py

Shall we enable yapf check also for the example folder?

format examples using yapf.

---

tensorlayer/layers/recurrent.py
tests/test_layers_recurrent.py

@nebulaV After [this commit](https://github.com/tensorlayer/tensorlayer/commit/025e874aa82058a54a131292f172ac00edb5f239#diff-dffe1d7a32e99bc0c815dedb99c8a90e), all RNN layers with `n_layer` can't work when `n_layer > 1` .
I updated the test code for `recurrent.py` here [test_layers_recurrent.py](https://github.com/tensorlayer/tensorlayer/blob/master/tests/test_layers_recurrent.py), could you please fix this bug? The robot will help to check the bugs, or you can run the test script locally. 
Many thanks.

update test code for recurrent & fix the bug for n_layer>1

---

tensorlayer/files.py
tests/test_mnist_simple.py

* Add support for Fashion-MNIST dataset #399 
* Add related tests in  [tests/test_mnist_simple.py](https://github.com/tensorlayer/tensorlayer/blob/master/tests/test_mnist_simple.py)

Add support for Fashion-MNIST dataset

---

docs/modules/layers.rst
tensorlayer/layers/convolution.py
tests/test_layers_convolution.py

This layer performs a depthwise convolution that acts separately on channels, followed by a pointwise convolution that mixes channels. 
While DepthwiseConv2d performs depth wise convolution only.

release seperable conv2d

---

.style.yapf
.travis.yml
README.md

* Make sure the Docker image is updated to the latest version
* update `.travis.yml` for testing `docker image build`

Make sure the Docker image is vaild

---

LICENSE.rst
docs/conf.py

update year to 2018

---

docs/modules/layers.rst

update docs - customizing layer

---

docs/user/tutorial.rst

**See Line no.:** 11, 15, 29, 120-122, 268, 283, 286, 298, 300, 372, 379, 398, 400, 489, 508, 596, 598, 997, 1006, 1286, 1709 and 1810.

Fixed various typos, Punctuation and grammar mistakes.

---

docs/modules/prepro.rst
docs/modules/visualize.rst
tensorlayer/prepro.py
tensorlayer/visualize.py

- draw_mpii_people_to_image --> draw_mpii_pose_to_image
- obj_box_left_right_flip --> obj_box_horizontal_flip

rename APIs of obj detection and pose

---

docs/modules/files.rst
tensorlayer/db.py
tensorlayer/files.py
tensorlayer/visualize.py

update docs 

---

tensorlayer/db.py

Small Fix to raise an error if pymongo is not installed.

pymongo import error fix

---

.travis.yml
README.rst
requirements.txt
setup.py
tensorlayer/__init__.py

A small update to improve the setup.py structure and various package informations.
This should make the package easier to maintain.
Changelog:
- Numerous information moved from **setup.py** to **tensorlayer/__init__.py**
- A copy of Readme.md has been added in restructured for PyPI.
- Package Requirements have been moved to file: **"requirements.txt"**
- New package information added to setup.py

Package arch refactoring

---

docs/requirements.txt

- update requirement.txt for readthedocs for progressbar2

fix docs for progressbar2

---

docs/requirements.txt

see https://github.com/tensorflow/tensorflow/issues/17441 for more details

revert tensorflow to 1.5.0 in docs build

---

README.md

Slack Logo resized from 50% to 40%

Slack css media

---

tensorlayer/layers/pooling.py

Fix bug report in https://github.com/tensorlayer/tensorlayer/issues/551

fix bug  #551

---

docs/conf.py
tensorlayer/__init__.py

release 1.8.5

---

CHANGELOG.md
docs/user/more.rst
tensorlayer/layers/recurrent.py

Very simple PR to address issue #498 with the Deprecation Warning in `tl.layers.RNNLayer` with `inspect` package.Some new textSome new textSome new textSome new text

Issue #498 - Deprecation Warning Fix in `tl.layers.RNNLayer` with `inspect`

---

.github/stale.yml
.pyup.yml

No Update of the Changelog is required, it is already updated.
You can directly merge ;)

PyUP and Stale Bot Configuration Updated

---

CHANGELOG.md
tensorlayer/layers/importer.py
tensorlayer/layers/merge.py

Update the docs for **ElementwiseLambdaLayer**

update docs for elementwise-lambda-layer

---

.github/changelog.yml
CHANGELOG.md

Configuration for https://github.com/mikz/probot-changelog

Changelog Config Bot added

---

.circleci/config.yml

Error fix for Docker builds on master branch. Duplicate Job not ignored

---

tensorlayer/__init__.py

A Quick Fix for RTD not compiling anymore for a while

RTD Compilation Fix

---

.travis.yml
CHANGELOG.md
README.md
README.rst
docs/conf.py
docs/modules/layers.rst
setup.travis.cfg
setup.travis_doc.cfg
tensorlayer/__init__.py
tensorlayer/layers/binary.py
tensorlayer/layers/convolution.py
tensorlayer/layers/core.py
tensorlayer/layers/extend.py
tensorlayer/layers/importer.py
tensorlayer/layers/inputs.py
tensorlayer/layers/normalization.py
tensorlayer/layers/object_detection.py
tensorlayer/layers/padding.py
tensorlayer/layers/pooling.py
tensorlayer/layers/shape.py
tensorlayer/layers/spatial_transformer.py
tensorlayer/layers/special_activation.py
tensorlayer/layers/stack.py
tensorlayer/layers/super_resolution.py
tests/test_layers_stack.py

Fix in logging.info Layer Name not displaying the full scope.
Release of 1.8.6rc3

Tl logging layer name fix

---

CHANGELOG.md

CHANGELOG for 1.8.6 official release

---

docs/modules/layers.rst

fix docs - wrong name

---

CHANGELOG.md
docs/modules/layers.rst

update docs - bianry net

---

CHANGELOG.md
docs/modules/layers.rst
tensorlayer/prepro.py

Fix https://github.com/tensorlayer/tensorlayer/issues/709

Missing import in prepro

---

tensorlayer/files/dataset_loaders/ptb_dataset.py

flake8 testing of https://github.com/tensorlayer/tensorlayer on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tensorlayer/files/dataset_loaders/ptb_dataset.py:61:18: F821 undefined name 'nlp'
word_to_id = nlp.build_vocab(nlp.read_words(train_path))
^
./tensorlayer/files/dataset_loaders/ptb_dataset.py:61:34: F821 undefined name 'nlp'
word_to_id = nlp.build_vocab(nlp.read_words(train_path))
^
./tensorlayer/files/dataset_loaders/ptb_dataset.py:63:18: F821 undefined name 'nlp'
train_data = nlp.words_to_word_ids(nlp.read_words(train_path), word_to_id)
^
./tensorlayer/files/dataset_loaders/ptb_dataset.py:63:40: F821 undefined name 'nlp'
train_data = nlp.words_to_word_ids(nlp.read_words(train_path), word_to_id)
^ …
```

from tensorlayer import nlp in ptb_dataset.py

---

tensorlayer/files/dataset_loaders/imdb_dataset.py

flake8 testing of https://github.com/tensorlayer/tensorlayer on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tensorlayer/files/dataset_loaders/imdb_dataset.py:59:13: F821 undefined name 'gzip'
f = gzip.open(os.path.join(path, filename), 'rb')
^
./tensorlayer/files/dataset_loaders/imdb_dataset.py:63:17: F821 undefined name 'cPickle'
X, labels = cPickle.load(f)
^
```

import cPickle, gzip in imdb_dataset.py

---

tensorlayer/nlp.py

Change to match line 20 and resolve _undefined names_ which have the potential to raise NameError at runtime.
flake8 testing of https://github.com/tensorlayer/tensorlayer on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tensorlayer/nlp.py:283:13: F821 undefined name 'tl'
tl.logging.fatal("Vocab file %s not found." % vocab_file)
^
./tensorlayer/nlp.py:284:9: F821 undefined name 'tl'
tl.logging.info("Initializing vocabulary from file: %s" % vocab_file)
^
./tensorlayer/nlp.py:1102:9: F821 undefined name 'tl'
tl.logging.info("Unable to fetch multi-bleu.perl script, using local.")
^
./tensorlayer/nlp.py:1130:17: F821 undefined name 'tl'
tl.logging.warning("multi-bleu.perl script returned non-zero exit code")
^ …
```

Typo: Change tl.logging --> logging in nlp.py

---

tensorlayer/files/utils.py

Update load file list -- enable keeping path in the file name

Update load file list -- enable keeping path in the file name

---

CHANGELOG.md
tensorlayer/models/vgg16.py
tensorlayer/models/vgg19.py

Update docs of vgg16 and vgg19

---

CHANGELOG.md
docs/modules/layers.rst
tensorlayer/layers/normalization.py
tests/test_layers_normalization.py

Switch Normalisation
https://zhuanlan.zhihu.com/p/39296570?utm_source=wechat_session&utm_medium=social&utm_oi=984862267107651584

release switch norm layer

---

docs/modules/layers.rst

layer --> Layer
layers --> Layers

update docs format - Layer(s)

---

docs/modules/layers.rst

`tl.act.identity` no longer exist. no changelog require.

Remove identity activation in the example code

---

CHANGELOG.md
tensorlayer/cost.py

Fix some typos

---

docs/modules/layers.rst

update layer docs

---

CHANGELOG.md
tensorlayer/distributed.py

1.fix the bug of scaling the learning rate of trainer

fix the bug of scaling the learning rate of trainer

---

tensorlayer/layers/utils.py

Merge network API supports graph, no need to change log.
please merge.

Merge network API supports graph

---

.travis.yml
CHANGELOG.md
README.md
tensorlayer/cost.py

Changelog Fix + Travis Optimization

---

CHANGELOG.md
requirements/requirements_test.txt

Dependency fix

---

CHANGELOG.md
tensorlayer/files/utils.py

fix log level for load_and_assign_npz and load_and_assign_npz_dict

---

tensorlayer/nlp.py
tensorlayer/package_info.py
tensorlayer/prepro.py
tensorlayer/visualize.py

New release

---

docs/modules/distributed.rst
docs/modules/layers.rst
tensorlayer/package_info.py

Fix the docs and release 1.10.0

[pls merge] docs and release

---

examples/README.md

Update README.md of Example

---

examples/README.md

Fix broken link

---

examples/distributed_training/tutorial_cifar10_distributed_trainer.py
examples/distributed_training/tutorial_mnist_distributed_trainer.py

increase prefetch distributed example

---

examples/basic_tutorials/tutorial_cifar10_datasetapi.py
examples/basic_tutorials/tutorial_cifar10_placeholder.py
examples/basic_tutorials/tutorial_cifar10_tfrecord.py
examples/data_process/tutorial_tf_dataset_voc.py
examples/distributed_training/tutorial_cifar10_distributed_trainer.py
examples/quantized_net/tutorial_binarynet_cifar10_tfrecord.py
examples/quantized_net/tutorial_dorefanet_cifar10_tfrecord.py
examples/quantized_net/tutorial_ternaryweight_cifar10_tfrecord.py
examples/reinforcement_learning/tutorial_bipedalwalker_a3c_continuous_action.py
examples/reinforcement_learning/tutorial_frozenlake_dqn.py
tensorlayer/layers/normalization.py
tensorlayer/models/mobilenetv1.py

Batchnorm with decay

---

docs/modules/prepro.rst
tensorlayer/prepro.py

For pose estimation task, we should maintain the left and right information.

guide for pose estimation - flipping

---

tensorlayer/prepro.py

CV2 transform supports constant and replicate padding.

cv2 transform support 2 modes;

---

tensorlayer/files/utils.py

return false if load_and_assign fail to find a model

return false if load_and_assign fail to find a model

---

README.md

Link for documentation is incorrect.

Update README.md for doc link 

---

README.md

Update README.md, Fix badge 'last commits'

---

examples/reinforcement_learning/README.md

update readme
changes:
1. delete observation space in table
2. add paper links in table
3. adjust algorithm order in table
4. add authors information

Tl example readme preview

---

.travis.yml
CHANGELOG.md
README.md
docs/user/installation.rst

Support TensorFlow 2.0.0-beta1

---

tensorlayer/layers/core.py

Fix nested layer bugs when using layerlist as attribute.

Fix nested layer layerlist bug

---

docs/user/get_involved.rst

add intros to surgicalai

---

tensorlayer/layers/lambda_layers.py
tests/layers/test_layers_lambda.py

Update doc of lambda layer for better demonstration.
Update test of lambda layer to show the case when fn has weights and the weights are declared outside the fn.

minor update lambda layer doc and test

---

.travis.yml
CHANGELOG.md
README.md

Make TensorFlow 2.0 rc1 compatible release.

---

README.md

add free gpu section

---

tensorlayer/layers/normalization.py

fix @tf.function ,AttributeError

---

tensorlayer/models/vgg.py

Simple modification for rubustness of code. Otherwise all n_filters configured in a same layer_group must keep same, which is not neccessary.
Simple, please refer to the diff.

in_channels must equal to previous n_filter

---

docs/modules/layers.rst

add missing doc for ModelLayer and LayerList
see above.

add missing doc for ModelLayer and LayerList

---

tensorlayer/layers/embedding.py

Duplicate code is not good for maintenance.
Duplicate code removed.

refactoring: Deduplication

---

tensorlayer/layers/normalization.py
tensorlayer/layers/pooling.py
tensorlayer/models/vgg.py

(1)maxpool and batchnorm dataformat debuged,support "channels_first"
(2)vgg forward fixed

hyperpose compatible

---

tensorlayer/layers/normalization.py
tensorlayer/models/core.py

fix BatchNorm

---

tensorlayer/models/vgg.py

fix vgg link

---

.travis.yml
CHANGELOG.md
tensorlayer/package_info.py

release2.2.4

---

examples/basic_tutorials/tutorial_mnist_simple.py

fix tutorial_mnist_simple.py
